backend:
  - changed-files:
      - any: ['apps/backend/**/*']

listener:
  - changed-files:
      - any: ['apps/listener/**/*']

analytics:
  - changed-files:
      - any: ['apps/analytics/**/*']

shared-utils:
  - changed-files:
      - any: ['packages/shared_utils/**/*']

deployments:
  - changed-files:
      - any: ['deployments/**/*']

ci:
  - changed-files:
      - any: ['.github/**/*']

dependencies:
  - changed-files:
      - any: ['pyproject.toml', 'uv.lock']

documentation:
  - changed-files:
      - any: ['*.md']
