backend:
  - changed-files:
      - any-glob-to-any-file: ['apps/backend/**']

listener:
  - changed-files:
      - any-glob-to-any-file: ['apps/listener/**']

analytics:
  - changed-files:
      - any-glob-to-any-file: ['apps/analytics/**']

shared-utils:
  - changed-files:
      - any-glob-to-any-file: ['packages/shared_utils/**']

deployments:
  - changed-files:
      - any-glob-to-any-file: ['deployments/**']

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']

dependencies:
  - changed-files:
      - any-glob-to-any-file: ['pyproject.toml', 'uv.lock']

documentation:
  - changed-files:
      - any-glob-to-any-file: ['*.md', 'docs/**']
