[mypy]
python_version = 3.12
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
warn_unused_ignores = false

[mypy-apps.*.tests.*]
ignore_errors = true

[mypy-apps.backend.queries]
disable_error_code = call-overload, arg-type

[mypy-apps.backend.main]
disable_error_code = call-overload

[mypy-apps.analytics.long_term_macro]
disable_error_code = call-overload, attr-defined

[mypy-apps.analytics.seed_historical]
disable_error_code = union-attr

[mypy-apps.analytics.evaluate_performance]
disable_error_code = union-attr, arg-type

[mypy-apps.listener.scrapers.skinport]
disable_error_code = arg-type, annotation-unchecked
