"""add simulated_trades

Revision ID: 416f6e55f454
Revises: 4dbe99d0947c
Create Date: 2026-07-03 14:02:59.564327

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "416f6e55f454"
down_revision: str | Sequence[str] | None = "4dbe99d0947c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulated_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("purchase_price_cents", sa.Integer(), nullable=False),
        sa.Column("estimated_profit_cents", sa.Integer(), nullable=False),
        sa.Column("trigger_z_score", sa.Float(), nullable=False),
        sa.Column("simulated_buy_timestamp", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["market_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_simulated_trades_item_id"), "simulated_trades", ["item_id"], unique=False)
    op.create_index(
        op.f("ix_simulated_trades_simulated_buy_timestamp"),
        "simulated_trades",
        ["simulated_buy_timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulated_trades_simulated_buy_timestamp"), table_name="simulated_trades")
    op.drop_index(op.f("ix_simulated_trades_item_id"), table_name="simulated_trades")
    op.drop_table("simulated_trades")
    # ### end Alembic commands ###
