"""create_macro_baselines_table

Revision ID: 4dbe99d0947c
Revises: 91ce9a538078
Create Date: 2026-06-24 17:18:36.459825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbe99d0947c'
down_revision: Union[str, Sequence[str], None] = '91ce9a538078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_macro_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('latest_price_cents', sa.Integer(), nullable=False),
    sa.Column('rolling_30d_avg_cents', sa.Integer(), nullable=False),
    sa.Column('rolling_90d_avg_cents', sa.Integer(), nullable=False),
    sa.Column('drift_percent', sa.Float(), nullable=False),
    sa.Column('volatility_cents', sa.Integer(), nullable=False),
    sa.Column('avg_volume_30d', sa.Float(), nullable=False),
    sa.Column('support_floor_cents', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['market_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_macro_baselines_item_id'), 'item_macro_baselines', ['item_id'], unique=True)
    op.create_index(op.f('ix_item_macro_baselines_updated_at'), 'item_macro_baselines', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_macro_baselines_updated_at'), table_name='item_macro_baselines')
    op.drop_index(op.f('ix_item_macro_baselines_item_id'), table_name='item_macro_baselines')
    op.drop_table('item_macro_baselines')
    # ### end Alembic commands ###
