"""create_initial_tables

Revision ID: 91ce9a538078
Revises: 
Create Date: 2026-06-24 11:27:03.660411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91ce9a538078'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_hash_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_items_item_type'), 'market_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_market_items_market_hash_name'), 'market_items', ['market_hash_name'], unique=True)
    op.create_table('historical_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('median_price_cents', sa.Integer(), nullable=False),
    sa.Column('volume_sold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['market_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historical_prices_item_date', 'historical_prices', ['item_id', 'sale_date'], unique=False)
    op.create_table('live_market_ticks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('marketplace_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.Column('paint_index', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['market_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_market_ticks_float_value'), 'live_market_ticks', ['float_value'], unique=False)
    op.create_index(op.f('ix_live_market_ticks_inserted_at'), 'live_market_ticks', ['inserted_at'], unique=False)
    op.create_index(op.f('ix_live_market_ticks_item_id'), 'live_market_ticks', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_market_ticks_item_id'), table_name='live_market_ticks')
    op.drop_index(op.f('ix_live_market_ticks_inserted_at'), table_name='live_market_ticks')
    op.drop_index(op.f('ix_live_market_ticks_float_value'), table_name='live_market_ticks')
    op.drop_table('live_market_ticks')
    op.drop_index('ix_historical_prices_item_date', table_name='historical_prices')
    op.drop_table('historical_prices')
    op.drop_index(op.f('ix_market_items_market_hash_name'), table_name='market_items')
    op.drop_index(op.f('ix_market_items_item_type'), table_name='market_items')
    op.drop_table('market_items')
    # ### end Alembic commands ###
